# Generated by Django 5.2.8 on 2025-11-25 10:50

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("study_groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, help_text="외부 노출용 ID", unique=True)),
                ("title", models.CharField(help_text="공고 제목", max_length=50)),
                ("content", models.TextField(help_text="공고 내용")),
                ("estimated_fee", models.PositiveIntegerField(help_text="예상되는 강의 결제 비용")),
                (
                    "expected_headcount",
                    models.SmallIntegerField(
                        help_text="예상 모집 인원 (1~10명)",
                        validators=[
                            django.core.validators.MinValueValidator(1, message="최소 1명 이상이어야 합니다."),
                            django.core.validators.MaxValueValidator(10, message="최대 10명까지 모집 가능합니다."),
                        ],
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0, help_text="조회수")),
                (
                    "close_at",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 12, 9, 10, 50, 37, 189460, tzinfo=datetime.timezone.utc),
                        help_text="공고 마감일",
                    ),
                ),
                ("is_closed", models.BooleanField(default=False, help_text="공고 마감 상태")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="공고 생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="공고 수정일", null=True)),
                (
                    "author",
                    models.ForeignKey(
                        db_column="author_id",
                        help_text="공고 작성자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        db_column="study_group_id",
                        help_text="스터디 그룹",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments",
                        to="study_groups.studygroup",
                    ),
                ),
            ],
            options={
                "db_table": "recruitments",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["uuid"], name="idx_uuid"),
                    models.Index(fields=["study_group"], name="idx_study_group"),
                    models.Index(fields=["author"], name="idx_author"),
                    models.Index(fields=["is_closed", "-created_at"], name="idx_closed_created"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expected_headcount__gte", 1), ("expected_headcount__lte", 10)),
                        name="check_expected_headcount_range",
                    )
                ],
            },
        ),
    ]
