# Generated by Django 5.2.8 on 2025-11-26 04:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="close_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 4, 8, 47, 33294, tzinfo=datetime.timezone.utc),
                help_text="공고 마감일",
            ),
        ),
    ]
