# Generated by Django 5.2.8 on 2025-11-25 10:28

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
        ("study_groups", "0002_studygroup_delete_studygroupbasemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="close_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 9, 10, 28, 58, 763436, tzinfo=datetime.timezone.utc),
                help_text="공고 마감일",
            ),
        ),
        migrations.AlterField(
            model_name="recruitment",
            name="study_group",
            field=models.ForeignKey(
                db_column="study_group_id",
                help_text="스터디 그룹",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruitments",
                to="study_groups.studygroup",
            ),
        ),
    ]
