# Generated by Django 5.2.8 on 2025-11-27 03:30

from django.db import migrations, models

import apps.recruitment.models.recruitment


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="close_at",
            field=models.DateTimeField(
                default=apps.recruitment.models.recruitment.get_default_close_at, help_text="공고 마감일"
            ),
        ),
    ]
