# Generated by Django 5.2.8 on 2025-11-27 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_alter_recruitment_close_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 모든 테이블이 이미 존재하므로 빈 마이그레이션
    ]
