# Generated by Django 5.2.8 on 2025-11-26 06:48

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_alter_recruitment_close_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="close_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 6, 48, 34, 366921, tzinfo=datetime.timezone.utc),
                help_text="공고 마감일",
            ),
        ),
        migrations.CreateModel(
            name="RecruitmentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.URLField(help_text="S3 등에 업로드된 파일의 URL", max_length=255, unique=True)),
                ("file_name", models.CharField(help_text="사용자가 업로드한 원본 파일명", max_length=50)),
                (
                    "recruitment",
                    models.ForeignKey(
                        db_column="recruitment_id",
                        help_text="구인공고",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="recruitment.recruitment",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_attachments",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["recruitment", "-created_at"], name="idx_recruitment_created")],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.URLField(help_text="이미지 URL", max_length=500)),
                (
                    "recruitment",
                    models.ForeignKey(
                        db_column="recruitment_id",
                        help_text="구인공고",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="recruitment.recruitment",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_image",
                "indexes": [models.Index(fields=["recruitment", "-created_at"], name="idx_recruitment_img_created")],
            },
        ),
    ]
