# Generated by Django 5.2.1 on 2025-11-26 09:29

from django.db import migrations, models

import apps.recruitment.models.recruitment


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_alter_recruitment_close_at_recruitmentattachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="close_at",
            field=models.DateTimeField(
                default=apps.recruitment.models.recruitment.get_default_close_at, help_text="공고 마감일"
            ),
        ),
    ]
