# Generated by Django 5.2.8 on 2025-11-26 07:57

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_alter_recruitment_close_at_recruitmentattachment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="close_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 12, 10, 7, 57, 21, 310352, tzinfo=datetime.timezone.utc),
                help_text="공고 마감일",
            ),
        ),
        migrations.CreateModel(
            name="RecruitmentBookmarks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="북마크 생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="북마크 수정일시", null=True)),
                (
                    "recruitment_id",
                    models.ForeignKey(
                        db_column="recruitment_id",
                        help_text="공고 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_bookmarks",
                        to="recruitment.recruitment",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="북마크한 유저의 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_bookmarks",
                "indexes": [
                    models.Index(fields=["user_id"], name="recruitment_user_id_ebd039_idx"),
                    models.Index(fields=["recruitment_id"], name="recruitment_recruit_ceb2ff_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user_id", "recruitment_id"), name="pk_user_recruitment_bookmark")
                ],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentSearchLogs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keyword", models.CharField(help_text="검색어", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="공고 검색 기록 생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="공고 검색 기록 수정일시", null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_search_logs",
                "indexes": [
                    models.Index(fields=["keyword"], name="recruitment_keyword_66deb9_idx"),
                    models.Index(fields=["created_at"], name="recruitment_created_9a3679_idx"),
                ],
            },
        ),
    ]
