# Generated by Django 5.2.8 on 2025-11-27 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_tag_recruitmenttag_recruitmentattachment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="태그 이름", max_length=20, unique=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "recruitment", "tag", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        help_text="태그 연결된 구인 공고 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_tags",
                        to="recruitment.recruitment",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="모집 공고에 사용하는 태그 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_tags",
                        to="recruitment.tag",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_tags",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.URLField(help_text="S3 등에 업로드된 파일의 URL", max_length=255, unique=True)),
                ("file_name", models.CharField(help_text="사용자가 업로드한 원본 파일명", max_length=50)),
                (
                    "recruitment",
                    models.ForeignKey(
                        db_column="recruitment_id",
                        help_text="구인공고",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="recruitment.recruitment",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_attachments",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["recruitment", "-created_at"], name="idx_recruitment_created")],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentBookmarks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruitment_id",
                    models.ForeignKey(
                        db_column="recruitment_id",
                        help_text="공고 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_bookmarks",
                        to="recruitment.recruitment",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="북마크한 유저의 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_bookmarks",
                "indexes": [
                    models.Index(fields=["user_id"], name="recruitment_user_id_ebd039_idx"),
                    models.Index(fields=["recruitment_id"], name="recruitment_recruit_ceb2ff_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user_id", "recruitment_id"), name="pk_user_recruitment_bookmark")
                ],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.URLField(help_text="이미지 URL", max_length=500)),
                (
                    "recruitment",
                    models.ForeignKey(
                        db_column="recruitment_id",
                        help_text="구인공고",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="recruitment.recruitment",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_image",
                "indexes": [models.Index(fields=["recruitment", "-created_at"], name="idx_recruitment_img_created")],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentSearchLogs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(help_text="검색어", max_length=255)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        help_text="유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_search_logs",
                "indexes": [
                    models.Index(fields=["keyword"], name="recruitment_keyword_66deb9_idx"),
                    models.Index(fields=["created_at"], name="recruitment_created_9a3679_idx"),
                ],
            },
        ),
    ]
