# Generated by Django 5.2.8 on 2025-11-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0004_alter_recruitment_close_at"),
        ("recruitment", "0004_alter_recruitment_close_at_recruitmentbookmarks_and_more"),
    ]

    operations = []
