# Generated by Django 5.2.8 on 2025-11-27 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0006_alter_recruitmentbookmarks_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="태그 이름", max_length=20, unique=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "recruitment", "tag", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        help_text="태그 연결된 구인 공고 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_tags",
                        to="recruitment.recruitment",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="모집 공고에 사용하는 태그 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_tags",
                        to="recruitment.tag",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_tags",
            },
        ),
    ]
