# Generated by Django 5.2.8 on 2025-11-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("nickname", models.CharField(max_length=10, unique=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("gender", models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=1)),
                ("birthday", models.DateField()),
                ("profile_img_url", models.URLField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
