# Generated by Django 5.2.8 on 2025-11-27 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NO_LONGER_NEEDED", "서비스 이용할 시간이 없음"),
                            ("LACK_OF_INTEREST", "관심이 사라짐"),
                            ("TOO_DIFFICULT", "서비스를 이용하기가 너무 어려움"),
                            ("FOUND_BETTER_SERVICE", "더 좋은 대안을 찾음"),
                            ("PRIVACY_CONCERNS", "개인정보/보안 우려"),
                            ("POOR_SERVICE_QUALITY", "서비스 품질 불만"),
                            ("TECHNICAL_ISSUES", "기술적 문제(버그 등)"),
                            ("LACK_OF_CONTENT", "원하는 콘텐츠나 기능의 부족"),
                            ("OTHER", "기타"),
                        ],
                        max_length=100,
                    ),
                ),
                ("reason_detail", models.CharField(blank=True, default="", max_length=500)),
                ("due_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "withdrawals",
            },
        ),
    ]
