# Generated by Django 5.2.8 on 2025-12-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_withdrawal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="reason_detail",
            field=models.CharField(max_length=500),
        ),
    ]
