# Generated by Django 5.2.1 on 2025-12-01 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_socialuser"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="socialuser",
            table="social_users",
        ),
    ]
