# Generated by Django 5.2.8 on 2025-12-08 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_withdrawal_reason_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawal",
            name="withdrawn_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
