# Generated by Django 5.2.8 on 2025-12-10 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_socialuser_table"),
        ("users", "0004_withdrawal_withdrawn_at"),
    ]

    operations = []
