# Generated by Django 5.2.8 on 2025-12-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_crawledlecture_categories"),
        ("users", "0006_socialuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lecture_bookmarks_middle_table",
            field=models.ManyToManyField(
                related_name="bookmark_by_users", through="lectures.LectureBookmark", to="lectures.crawledlecture"
            ),
        ),
    ]
