# Generated by Django 5.2.8 on 2025-12-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_crawledlecture_categories"),
        ("users", "0007_user_lecture_bookmarks_middle_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="prefer_categories_middle_table",
            field=models.ManyToManyField(
                related_name="category_by_users", through="lectures.UserPreferCategory", to="lectures.category"
            ),
        ),
    ]
