# Generated by Django 5.2.8 on 2025-12-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_prefer_categories_middle_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
