# Generated by Django 5.2.8 on 2025-11-28 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("study_groups", "0003_alter_studygroup_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("ai_summary", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        db_column="study_group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="study_groups.studygroup",
                    ),
                ),
            ],
            options={
                "db_table": "study_notes",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StudyNoteAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.URLField(unique=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "study_note",
                    models.ForeignKey(
                        db_column="study_note_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="note.studynote",
                    ),
                ),
            ],
            options={
                "db_table": "study_note_attachments",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StudyNoteImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.URLField()),
                (
                    "study_note",
                    models.ForeignKey(
                        db_column="study_note_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="note.studynote",
                    ),
                ),
            ],
            options={
                "db_table": "study_note_images",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="studynote",
            index=models.Index(fields=["study_group"], name="idx_study_note_group"),
        ),
        migrations.AddIndex(
            model_name="studynote",
            index=models.Index(fields=["author"], name="idx_study_note_author"),
        ),
        migrations.AddIndex(
            model_name="studynoteattachment",
            index=models.Index(fields=["study_note"], name="idx_note_attachment_note"),
        ),
        migrations.AddIndex(
            model_name="studynoteimage",
            index=models.Index(fields=["study_note"], name="idx_note_image_note"),
        ),
    ]
