# Generated by Django 5.2.8 on 2025-11-27 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STUDY_JOIN", "스터디 그룹에 새로운 구성원이 참가한 경우 알림"),
                            ("STUDY_NOTE_CREATE", "스터디 구성원이 스터디 기록을 작성한 경우 알림"),
                            ("STUDY_REVIEW_REQUEST", "스터디 종료가 도래한 경우 알림"),
                            ("APPLICATION_ACCEPT", "지원내역이 승인된 경우 알림"),
                            ("APPLICATION_REJECT", "지원내역이 거절된 경우 알림"),
                            ("ADD_APPLICATION", "공고를 올린 스터디 그룹의 리더에게 새로운 지원내역이 있는 경우 알림"),
                            ("TODAY_SCHEDULE", "금일 스케줄 알림"),
                            ("UPCOMING_SCHEDULE", "스케줄 하루 전에 임박한 예정 스케줄 알림"),
                        ]
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("back_url_link", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "indexes": [models.Index(fields=["user", "is_read"], name="notificatio_user_id_d569bc_idx")],
            },
        ),
    ]
