# Generated by Django 5.2.8 on 2025-12-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("STUDY_JOIN", "스터디 그룹에 새로운 구성원이 참가한 경우 알림"),
                    ("STUDY_NOTE_CREATE", "스터디 구성원이 스터디 기록을 작성한 경우 알림"),
                    ("STUDY_REVIEW_REQUEST", "스터디 종료가 도래한 경우 알림"),
                    ("APPLICATION_ACCEPT", "지원내역이 승인된 경우 알림"),
                    ("APPLICATION_REJECT", "지원내역이 거절된 경우 알림"),
                    ("ADD_APPLICATION", "공고를 올린 스터디 그룹의 리더에게 새로운 지원내역이 있는 경우 알림"),
                    ("TODAY_SCHEDULE", "금일 스케줄 알림"),
                    ("UPCOMING_SCHEDULE", "스케줄 하루 전에 임박한 예정 스케줄 알림"),
                ],
                max_length=300,
            ),
        ),
    ]
