# Generated by Django 5.2.8 on 2025-11-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("study_groups", "0002_groupmember_studylecture"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="스케줄 제목", max_length=100)),
                ("objective", models.CharField(blank=True, help_text="스케줄 설명", max_length=500, null=True)),
                ("session_date", models.DateTimeField(help_text="스케줄 날짜")),
                ("start_time", models.TimeField(help_text="시작 시간")),
                ("end_time", models.TimeField(help_text="종료 시간")),
                (
                    "study_group",
                    models.ForeignKey(
                        db_column="study_group_id",
                        help_text="스터디 그룹",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="study_groups.studygroup",
                    ),
                ),
            ],
            options={
                "db_table": "group_schedules",
            },
        ),
        migrations.CreateModel(
            name="ScheduleParticipants",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        help_text="참가 맴버",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="study_groups.groupmember",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="schedule_id",
                        help_text="스케줄",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="schedule.groupschedule",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_participants",
            },
        ),
    ]
