# Generated by Django 5.2.8 on 2025-11-27 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
        ("study_groups", "0002_alter_studygroup_table_groupmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleParticipantsModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        help_text="참가 맴버",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="study_groups.groupmember",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="schedule_id",
                        help_text="스케줄",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="schedule.groupschedulemodel",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_participants",
            },
        ),
    ]
