# Generated by Django 5.2.8 on 2025-11-26 05:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recruitment", "0002_alter_recruitment_close_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, help_text="보안을 위한 식별자", unique=True),
                ),
                ("objective", models.CharField(help_text="지원 목표", max_length=300)),
                ("motivation", models.TextField(help_text="지원 동기")),
                ("self_introduction", models.TextField(help_text="자기 소개")),
                (
                    "available_time",
                    models.CharField(help_text="예시: 주 2회, 월/수 저녁 7시 이후 참여 가능", max_length=100),
                ),
                (
                    "has_study_experience",
                    models.BooleanField(default=False, help_text="과거에 스터디 참여한 경험이 있는지 여부"),
                ),
                ("study_experience", models.TextField(blank=True, help_text="스터디 경험이 있다면 기재해주세요")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("CANCELED", "취소됨"),
                            ("ACCEPTED", "승인됨"),
                            ("REJECTED", "거절됨"),
                        ],
                        default="PENDING",
                        help_text="지원서 현재 진행 상태(대기, 취소 ,승인, 거절)",
                        max_length=20,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="지원자가 지원한 공고",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        help_text="지원한 공고",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="recruitment.recruitment",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "indexes": [
                    models.Index(
                        fields=["recruitment", "status", "-created_at"], name="application_recruit_39eaf8_idx"
                    ),
                    models.Index(fields=["applicant", "-created_at"], name="application_applica_bfaf5a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("applicant", "recruitment"), name="unique_application_per_applicant_per_recruitment"
                    )
                ],
            },
        ),
    ]
