# Generated by Django 5.2.8 on 2025-11-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawledLectures",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.BigIntegerField(help_text="크롤링 한 사이트에서 받은 강의의 pk")),
                ("title", models.CharField(help_text="강의명", max_length=255)),
                ("instructor", models.CharField(help_text="강사명", max_length=20)),
                ("average_rating", models.DecimalField(decimal_places=2, help_text="리뷰 평점", max_digits=3)),
                ("total_class_time", models.SmallIntegerField(help_text="총 강의 시간")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("EASY", "초급"), ("NORMAL", "중급"), ("HARD", "어려움")],
                        help_text="강의 난이도",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="간략한 강의 상세 설명")),
                (
                    "platform",
                    models.CharField(
                        choices=[("INFLEARN", "인프런"), ("UDEMY", "유데미")], help_text="플랫폼", max_length=20
                    ),
                ),
                ("original_price", models.BigIntegerField(blank=True, default=0, help_text="강의 원가격", null=True)),
                ("discount_price", models.BigIntegerField(blank=True, default=0, help_text="강의 할인가격", null=True)),
                ("url_link", models.URLField(help_text="강의 바로가기 링크", max_length=255)),
                (
                    "thumbnail_img_url",
                    models.URLField(blank=True, help_text="강의 썸네일 이미지", max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(fields=("platform", "external_id"), name="unique_platform_external_id")
                ],
            },
        ),
    ]
