# Generated by Django 5.2.8 on 2025-11-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawledLectureReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.BigIntegerField(help_text="크롤링 한 사이트에서 받은 리뷰의 pk")),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[(5, "5점"), (4, "4점"), (3, "3점"), (2, "2점"), (1, "1점")], help_text="리뷰의 평점"
                    ),
                ),
                ("content", models.TextField(help_text="리뷰 내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        help_text="리뷰가 달린 강의의 id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="lectures.crawledlecture",
                    ),
                ),
            ],
            options={
                "db_table": "crawled_lecture_reviews",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(fields=("lecture", "external_id"), name="unique_lecture_review")
                ],
            },
        ),
    ]
