# Generated by Django 5.2.8 on 2025-11-27 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="카테고리명", max_length=255, unique=True)),
            ],
            options={
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LectureBookmark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user", "lecture", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="lectures.crawledlecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lecture_bookmarks",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LectureCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "lecture_id", "category_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="카테고리 id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_lectures",
                        to="lectures.category",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        help_text="강의 id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_categories",
                        to="lectures.crawledlecture",
                    ),
                ),
            ],
            options={
                "db_table": "lecture_categories",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "category_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="카테고리 id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_by_users",
                        to="lectures.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="유저 id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_prefer_categories",
                "ordering": ["pk"],
            },
        ),
    ]
