# Generated by Django 5.2.8 on 2025-11-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_crawledlecturereview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="카테고리명", max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LectureCategory",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "lecture_id",
                        "category_id",
                        blank=True,
                        editable=False,
                        help_text="복합키",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="카테고리 id", on_delete=django.db.models.deletion.CASCADE, to="lectures.category"
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        help_text="강의 id", on_delete=django.db.models.deletion.CASCADE, to="lectures.crawledlecture"
                    ),
                ),
            ],
            options={
                "db_table": "lecture_categories",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferCategory",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "category_id",
                        blank=True,
                        editable=False,
                        help_text="복합 pk키",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="카테고리 id", on_delete=django.db.models.deletion.CASCADE, to="lectures.category"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="유저 id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_prefer_categories",
                "ordering": ["pk"],
            },
        ),
    ]
