# Generated by Django 5.2.8 on 2025-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_category_lecturebookmark_lecturecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawledlecture",
            name="categories",
            field=models.ManyToManyField(
                related_name="lectures", through="lectures.LectureCategory", to="lectures.category"
            ),
        ),
    ]
