# Generated by Django 5.2.8 on 2025-11-26 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_category_lecturecategory_userprefercategory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturecategory",
            name="category",
            field=models.ForeignKey(
                help_text="카테고리 id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_lectures",
                to="lectures.category",
            ),
        ),
        migrations.AlterField(
            model_name="lecturecategory",
            name="lecture",
            field=models.ForeignKey(
                help_text="강의 id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecture_categories",
                to="lectures.crawledlecture",
            ),
        ),
        migrations.AlterField(
            model_name="lecturecategory",
            name="pk",
            field=models.CompositePrimaryKey(
                "lecture_id", "category_id", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="userprefercategory",
            name="category",
            field=models.ForeignKey(
                help_text="카테고리 id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_by_users",
                to="lectures.category",
            ),
        ),
        migrations.AlterField(
            model_name="userprefercategory",
            name="pk",
            field=models.CompositePrimaryKey(
                "user_id", "category_id", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="userprefercategory",
            name="user",
            field=models.ForeignKey(
                help_text="유저 id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
