# Generated by Django 5.2.8 on 2025-11-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
                ("introduction", models.CharField(blank=True, max_length=500, null=True)),
                ("max_headcount", models.SmallIntegerField()),
                ("profile_img_url", models.URLField(blank=True, null=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("ONGOING", "Ongoing"), ("ENDED", "Ended")],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "study_groups",
            },
        ),
        migrations.DeleteModel(
            name="StudyGroupBaseModel",
        ),
    ]
