# Generated by Django 5.2.8 on 2025-11-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_groups", "0002_groupmember_studylecture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studygroup",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(fields=["name"], name="idx_study_group_name"),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(fields=["status"], name="idx_study_group_status"),
        ),
        migrations.AddConstraint(
            model_name="studygroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_headcount__gte", 2), ("max_headcount__lte", 10)),
                name="check_study_group_max_headcount_range",
            ),
        ),
    ]
