# Generated by Django 5.2.8 on 2025-11-28 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_groups", "0003_alter_studygroup_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="스케줄 제목", max_length=100)),
                ("objective", models.CharField(blank=True, help_text="스케줄 설명", max_length=500, null=True)),
                ("session_date", models.DateTimeField(help_text="스케줄 날짜")),
                ("start_time", models.TimeField(help_text="시작 시간")),
                ("end_time", models.TimeField(help_text="종료 시간")),
                (
                    "study_group",
                    models.ForeignKey(
                        db_column="study_group_id",
                        help_text="스터디 그룹",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="study_groups.studygroup",
                    ),
                ),
            ],
            options={
                "db_table": "group_schedules",
            },
        ),
        migrations.CreateModel(
            name="ScheduleParticipants",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        help_text="참가 맴버",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="study_groups.groupmember",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="schedule_id",
                        help_text="스케줄",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="study_groups.groupschedule",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_participants",
            },
        ),
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("ai_summary", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        db_column="study_group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="study_groups.studygroup",
                    ),
                ),
            ],
            options={
                "db_table": "study_notes",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StudyNoteAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.URLField(unique=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "study_note",
                    models.ForeignKey(
                        db_column="study_note_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="study_groups.studynote",
                    ),
                ),
            ],
            options={
                "db_table": "study_note_attachments",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StudyNoteImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_url", models.URLField()),
                (
                    "study_note",
                    models.ForeignKey(
                        db_column="study_note_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="study_groups.studynote",
                    ),
                ),
            ],
            options={
                "db_table": "study_note_images",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="studynote",
            index=models.Index(fields=["study_group"], name="idx_study_note_group"),
        ),
        migrations.AddIndex(
            model_name="studynote",
            index=models.Index(fields=["author"], name="idx_study_note_author"),
        ),
        migrations.AddIndex(
            model_name="studynoteattachment",
            index=models.Index(fields=["study_note"], name="idx_note_attachment_note"),
        ),
        migrations.AddIndex(
            model_name="studynoteimage",
            index=models.Index(fields=["study_note"], name="idx_note_image_note"),
        ),
    ]
