# Generated by Django 5.2.8 on 2025-12-01 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_groups", "0004_groupschedule_scheduleparticipants_studynote_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "star_rating",
                    models.IntegerField(
                        choices=[
                            (5, "5_OUT_OF_5_STARS"),
                            (4, "4_OUT_OF_5_STARS"),
                            (3, "3_OUT_OF_5_STARS"),
                            (2, "2_OUT_OF_5_STARS"),
                            (1, "1_OUT_OF_5_STARS"),
                        ]
                    ),
                ),
                ("content", models.CharField(max_length=300)),
                (
                    "study_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="study_groups.studygroup"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "reviews",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "study_group"), name="unique_user_study_group_review")
                ],
            },
        ),
    ]
