# Generated by Django 5.2.8 on 2025-12-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study_groups", "0005_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupmember",
            old_name="study_group_id",
            new_name="study_group",
        ),
        migrations.RenameField(
            model_name="groupmember",
            old_name="user_id",
            new_name="user",
        ),
    ]
