# Generated by Django 5.2.9 on 2025-12-05 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_groups", "0005_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="studylecture",
            old_name="lecture_id",
            new_name="lecture",
        ),
        migrations.RenameField(
            model_name="studylecture",
            old_name="study_group_id",
            new_name="study_group",
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="study_group_id",
            field=models.ForeignKey(
                db_column="study_group_id", on_delete=django.db.models.deletion.CASCADE, to="study_groups.studygroup"
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
