# Generated by Django 5.2.9 on 2025-12-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_crawledlecture_categories"),
        ("study_groups", "0006_rename_lecture_id_studylecture_lecture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studylecture",
            name="lecture",
            field=models.ForeignKey(
                db_column="lecture_id", on_delete=django.db.models.deletion.CASCADE, to="lectures.crawledlecture"
            ),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="study_group",
            field=models.ForeignKey(
                db_column="study_group_id", on_delete=django.db.models.deletion.CASCADE, to="study_groups.studygroup"
            ),
        ),
    ]
