# Generated by Django 5.2.8 on 2025-12-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study_groups", "0006_rename_study_group_id_groupmember_study_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studylecture",
            old_name="lecture_id",
            new_name="lecture",
        ),
        migrations.RenameField(
            model_name="studylecture",
            old_name="study_group_id",
            new_name="study_group",
        ),
    ]
