# Generated by Django 5.2.8 on 2025-12-11 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_crawledlecture_categories"),
        ("study_groups", "0008_alter_groupmember_user_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="study_group_id",
            field=models.ForeignKey(
                db_column="study_group_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupmember_study_groups",
                to="study_groups.studygroup",
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupmember_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="lecture",
            field=models.ForeignKey(
                db_column="studylecture_lectures",
                on_delete=django.db.models.deletion.CASCADE,
                to="lectures.crawledlecture",
            ),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="study_group",
            field=models.ForeignKey(
                db_column="studylecture_study_groups",
                on_delete=django.db.models.deletion.CASCADE,
                to="study_groups.studygroup",
            ),
        ),
    ]
