# Generated by Django 5.2.8 on 2025-12-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_crawledlecture_categories"),
        ("study_groups", "0010_alter_review_study_group_alter_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studylecture",
            name="lecture",
            field=models.ForeignKey(
                db_column="lecture_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studylecture_lectures",
                to="lectures.crawledlecture",
            ),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="study_group",
            field=models.ForeignKey(
                db_column="stuudy_group_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studylecture_study_groups",
                to="study_groups.studygroup",
            ),
        ),
    ]
