# Generated by Django 5.2.8 on 2025-12-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_groups", "0011_alter_studylecture_lecture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studylecture",
            name="study_group",
            field=models.ForeignKey(
                db_column="study_group_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studylecture_study_groups",
                to="study_groups.studygroup",
            ),
        ),
    ]
