# Generated by Django 5.2.1 on 2025-11-26 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("study_groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lastreadmessage",
            name="unique_user_per_study_group",
        ),
        migrations.RemoveField(
            model_name="lastreadmessage",
            name="message_id",
        ),
        migrations.AddField(
            model_name="lastreadmessage",
            name="message",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_read_by_users",
                to="chat.chatmessage",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["study_group", "created_at"], name="chat_messag_study_g_1756ed_idx"),
        ),
        migrations.AddConstraint(
            model_name="lastreadmessage",
            constraint=models.UniqueConstraint(fields=("study_group", "user"), name="unique_user_group_last_read"),
        ),
    ]
