# Generated by Django 5.2.8 on 2025-11-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_lastreadmessage_unique_user_per_study_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lastreadmessage",
            name="message",
        ),
        migrations.RemoveField(
            model_name="lastreadmessage",
            name="study_group",
        ),
        migrations.RemoveField(
            model_name="lastreadmessage",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="LastReadMessage",
        ),
    ]
