# Generated by Django 5.2.1 on 2025-11-26 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0003_remove_lastreadmessage_message_and_more"),
        ("study_groups", "0002_alter_studygroup_table_groupmember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(max_length=1000)),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="study_groups.studygroup",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
            },
        ),
        migrations.CreateModel(
            name="LastReadMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_read_by_users",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_read_messages",
                        to="study_groups.studygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_read_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "last_read_messages",
            },
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["study_group", "created_at"], name="chat_messag_study_g_1756ed_idx"),
        ),
        migrations.AddConstraint(
            model_name="lastreadmessage",
            constraint=models.UniqueConstraint(fields=("study_group", "user"), name="unique_user_group_last_read"),
        ),
    ]
